# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/BHaType/Documents/GitHub/actions.ext

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/BHaType/Documents/GitHub/actions.ext

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/BHaType/Documents/GitHub/actions.ext/CMakeFiles /mnt/c/Users/BHaType/Documents/GitHub/actions.ext/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/BHaType/Documents/GitHub/actions.ext/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named actions.ext.2.l4d2

# Build rule for target.
actions.ext.2.l4d2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 actions.ext.2.l4d2
.PHONY : actions.ext.2.l4d2

# fast build rule for target.
actions.ext.2.l4d2/fast:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/build
.PHONY : actions.ext.2.l4d2/fast

mnt/d/sourcemod/public/smsdk_ext.o: mnt/d/sourcemod/public/smsdk_ext.cpp.o

.PHONY : mnt/d/sourcemod/public/smsdk_ext.o

# target to build an object file
mnt/d/sourcemod/public/smsdk_ext.cpp.o:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/mnt/d/sourcemod/public/smsdk_ext.cpp.o
.PHONY : mnt/d/sourcemod/public/smsdk_ext.cpp.o

mnt/d/sourcemod/public/smsdk_ext.i: mnt/d/sourcemod/public/smsdk_ext.cpp.i

.PHONY : mnt/d/sourcemod/public/smsdk_ext.i

# target to preprocess a source file
mnt/d/sourcemod/public/smsdk_ext.cpp.i:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/mnt/d/sourcemod/public/smsdk_ext.cpp.i
.PHONY : mnt/d/sourcemod/public/smsdk_ext.cpp.i

mnt/d/sourcemod/public/smsdk_ext.s: mnt/d/sourcemod/public/smsdk_ext.cpp.s

.PHONY : mnt/d/sourcemod/public/smsdk_ext.s

# target to generate assembly for a file
mnt/d/sourcemod/public/smsdk_ext.cpp.s:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/mnt/d/sourcemod/public/smsdk_ext.cpp.s
.PHONY : mnt/d/sourcemod/public/smsdk_ext.cpp.s

source/actions/public/actions_manager.o: source/actions/public/actions_manager.cpp.o

.PHONY : source/actions/public/actions_manager.o

# target to build an object file
source/actions/public/actions_manager.cpp.o:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_manager.cpp.o
.PHONY : source/actions/public/actions_manager.cpp.o

source/actions/public/actions_manager.i: source/actions/public/actions_manager.cpp.i

.PHONY : source/actions/public/actions_manager.i

# target to preprocess a source file
source/actions/public/actions_manager.cpp.i:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_manager.cpp.i
.PHONY : source/actions/public/actions_manager.cpp.i

source/actions/public/actions_manager.s: source/actions/public/actions_manager.cpp.s

.PHONY : source/actions/public/actions_manager.s

# target to generate assembly for a file
source/actions/public/actions_manager.cpp.s:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_manager.cpp.s
.PHONY : source/actions/public/actions_manager.cpp.s

source/actions/public/actions_processor.o: source/actions/public/actions_processor.cpp.o

.PHONY : source/actions/public/actions_processor.o

# target to build an object file
source/actions/public/actions_processor.cpp.o:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_processor.cpp.o
.PHONY : source/actions/public/actions_processor.cpp.o

source/actions/public/actions_processor.i: source/actions/public/actions_processor.cpp.i

.PHONY : source/actions/public/actions_processor.i

# target to preprocess a source file
source/actions/public/actions_processor.cpp.i:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_processor.cpp.i
.PHONY : source/actions/public/actions_processor.cpp.i

source/actions/public/actions_processor.s: source/actions/public/actions_processor.cpp.s

.PHONY : source/actions/public/actions_processor.s

# target to generate assembly for a file
source/actions/public/actions_processor.cpp.s:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_processor.cpp.s
.PHONY : source/actions/public/actions_processor.cpp.s

source/actions/public/actions_propagate.o: source/actions/public/actions_propagate.cpp.o

.PHONY : source/actions/public/actions_propagate.o

# target to build an object file
source/actions/public/actions_propagate.cpp.o:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_propagate.cpp.o
.PHONY : source/actions/public/actions_propagate.cpp.o

source/actions/public/actions_propagate.i: source/actions/public/actions_propagate.cpp.i

.PHONY : source/actions/public/actions_propagate.i

# target to preprocess a source file
source/actions/public/actions_propagate.cpp.i:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_propagate.cpp.i
.PHONY : source/actions/public/actions_propagate.cpp.i

source/actions/public/actions_propagate.s: source/actions/public/actions_propagate.cpp.s

.PHONY : source/actions/public/actions_propagate.s

# target to generate assembly for a file
source/actions/public/actions_propagate.cpp.s:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/actions/public/actions_propagate.cpp.s
.PHONY : source/actions/public/actions_propagate.cpp.s

source/public/extension.o: source/public/extension.cpp.o

.PHONY : source/public/extension.o

# target to build an object file
source/public/extension.cpp.o:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/public/extension.cpp.o
.PHONY : source/public/extension.cpp.o

source/public/extension.i: source/public/extension.cpp.i

.PHONY : source/public/extension.i

# target to preprocess a source file
source/public/extension.cpp.i:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/public/extension.cpp.i
.PHONY : source/public/extension.cpp.i

source/public/extension.s: source/public/extension.cpp.s

.PHONY : source/public/extension.s

# target to generate assembly for a file
source/public/extension.cpp.s:
	$(MAKE) -f CMakeFiles/actions.ext.2.l4d2.dir/build.make CMakeFiles/actions.ext.2.l4d2.dir/source/public/extension.cpp.s
.PHONY : source/public/extension.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... actions.ext.2.l4d2"
	@echo "... mnt/d/sourcemod/public/smsdk_ext.o"
	@echo "... mnt/d/sourcemod/public/smsdk_ext.i"
	@echo "... mnt/d/sourcemod/public/smsdk_ext.s"
	@echo "... source/actions/public/actions_manager.o"
	@echo "... source/actions/public/actions_manager.i"
	@echo "... source/actions/public/actions_manager.s"
	@echo "... source/actions/public/actions_processor.o"
	@echo "... source/actions/public/actions_processor.i"
	@echo "... source/actions/public/actions_processor.s"
	@echo "... source/actions/public/actions_propagate.o"
	@echo "... source/actions/public/actions_propagate.i"
	@echo "... source/actions/public/actions_propagate.s"
	@echo "... source/public/extension.o"
	@echo "... source/public/extension.i"
	@echo "... source/public/extension.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

